### ISSUE TITLE
The demo can not be exited

### ISSUE THREAD

**Issue by volllly** [fiskaltrust/middleware-de-demo-dotnet#7]
Entering `exit` does not exit.

**Comment by TSchmiedlechner** [comment]
This seems to be a Powershell Core issue (https://github.com/PowerShell/PowerShell/issues/11314), updating to v7 did the trick for me. Could you try that and confirm? :)

**Comment by volllly** [comment]
@TSchmiedlechner the `ctrl`+`c` issue still exists but is a windows terminal / pwsh issue ^^

**Comment by TSchmiedlechner** [comment]
Thanks for reporting and fixing! Fixed by #8
